version: "3.9"
services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    build:
      context: ./server/
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    volumes:
      - type: bind
        source: /Users/florianparzefall/SynologyDrive/SynologyDrive/Trading/Tool/DB
        target: /db
    ports:
      - "3000:3000"
  client:
    image: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        - NODE_ENV=development
    build:
      context: ./client/
    ports:
      - '8080:8080'

